# Capítulo 5 - Ejercicios

### Ejercicio 1

Basado en el programa `primos.py` y la función `enc_primos.py`, escriba un programa que genere una matriz en la cual se organicen los números primos. Pero en este caso, organícelos en forma de hélice, es decir
```
2x2 matrix
[[ 2.  3.]
 [ 7.  5.]]
3x3 matrix
[[ 17.  19.  23.]
 [ 13.   2.   3.]
 [ 11.   7.   5.]]
4x4 matrix
[[ 17.  19.  23.  29.]
 [ 13.   2.   3.  31.]
 [ 11.   7.   5.  37.]
 [ 53.  47.  43.  41.]]
```
Permita que se pueda crear la matriz de diferentes tamaños (`5x5`, `6x6`, ...).

In [12]:
def reshape_prime(primes,isize=4):
    """
    Función para crear matriz en esperial
    con un número máximo de tamaño (nxn)
    El vector primes, debe tener los números
    primos que se quieren organizar
    Entradas:
       primes - arreglo con números en orden
    Opcional
       isize - tamaño de la matriz cuadrada
    Salidas
       c - matrix cuadrada en espiral
    """
    import numpy as np
    
    c = np.zeros((isize,isize))

    if (isize%2 == 1):
        i0 = round((isize+1)/2-1)
    else:
        i0 = round(isize/2)-1

    # Initial point
    i1 = i0
    j1 = i0
    c[i1,j1]=primes[0]

    # loop over spiral
    icnt = 0
    for k in range(isize):
        k0 = k+1
        if (k0%2 == 1):
            iplus = +1
        else:
            iplus = -1
        for j in range(k0):
            j1 = j1+1*iplus
            if (i1==isize or j1==isize or
                  i1< 0     or j1< 0):
                break
            icnt = icnt+1
            c[i1,j1] = primes[icnt]
        for i in range(k0):
            i1 = i1+1*iplus
            if (i1==isize or j1==isize or
                    i1< 0     or j1< 0):
                break
            icnt = icnt+1
            c[i1,j1] = primes[icnt]

    return c

In [14]:
# primos4.py

import clase.homework as hw
import numpy as np

# Primero, obtenga el vector con muchos primos
primes,nprime = hw.primos_vector(1000)
print ("# primos encontrados ", nprime)

# Ahora, reorganize matriz, con diferentes tamaños
c4 = reshape_prime(primes,4)
print("Matrix organized in spiral")
print(c4)

c = reshape_prime(primes,5)
print("Matrix organized in spiral")
print(c)

c = reshape_prime(primes,6)
print("Matrix organized in spiral")
print(c)

c = reshape_prime(primes,7)
print("Matrix organized in spiral")
print(c)




# primos encontrados  168
Matrix organized in spiral
[[17. 19. 23. 29.]
 [13.  2.  3. 31.]
 [11.  7.  5. 37.]
 [53. 47. 43. 41.]]
Matrix organized in spiral
[[73. 79. 83. 89. 97.]
 [71. 17. 19. 23. 29.]
 [67. 13.  2.  3. 31.]
 [61. 11.  7.  5. 37.]
 [59. 53. 47. 43. 41.]]
Matrix organized in spiral
[[ 73.  79.  83.  89.  97. 101.]
 [ 71.  17.  19.  23.  29. 103.]
 [ 67.  13.   2.   3.  31. 107.]
 [ 61.  11.   7.   5.  37. 109.]
 [ 59.  53.  47.  43.  41. 113.]
 [151. 149. 139. 137. 131. 127.]]
Matrix organized in spiral
[[191. 193. 197. 199. 211. 223. 227.]
 [181.  73.  79.  83.  89.  97. 101.]
 [179.  71.  17.  19.  23.  29. 103.]
 [173.  67.  13.   2.   3.  31. 107.]
 [167.  61.  11.   7.   5.  37. 109.]
 [163.  59.  53.  47.  43.  41. 113.]
 [157. 151. 149. 139. 137. 131. 127.]]


### Ejercicio 2

Un análisis simple de una serie de datos incluye el cálculo del promedio (mean) y la desviación estandard (std). Sin embargo, algunos datos tienen distribuciones estadísticas que no son normales (gaussiana), y una mejor descripción del valor medio de los datos se obtiene con la mediana (median). Para calcular la mediana, se requiere organizar los datos de manera ascendente y así determinar la mediana. Una función que permite reorganizar un arreglo de números utiliza el método de `quicksort`, disponible en mi caso en el módulo.

Cree dos arreglos de 50 y 51 números aleatorios con {\tt numpy} y con funciones determine el promedio, desviación estándar y la mediana del arreglo. No utilice funciones propias de Python para el cálculo. Compare sus resultados con las funciones {\tt np.mean} y {\tt np.median}. 

Puede usar
```
C = np.random.normal(0,1,51)
```
para crear su arreglo. 


In [11]:
def median(data):
   """ 
   Función que calcula la mediana de un arreglo
   Entradas
      data - array with numbers, unsorted
   Salidas
      med - median 
   """
   import clase.homework as hw
    
   d_sorted = hw.quicksort(data)
   n = d_sorted.size

   if (n%2 == 0):   # Even number of data points
      i1 = round(n/2  -1)
      i2 = round(i1+1 )
      med = (d_sorted[i1] + d_sorted[i2])/2.
   else:
      i1 = round((n+1)/2 - 1)
      med = d_sorted[i1]
   
   return med

def mn_std(data):
   """ 
   Función que calcula promedio y 
   desviación estandar.
   Entradas
      data - array with numbers, unsorted
   Salidas
      mn  - promedio (mean)
      std - desviación estandar 
   """
   import numpy as np
    
   n  = data.size
   mn = np.sum(data)/n

   dev = np.sum((data-mn)**2)
   std = np.sqrt(dev/(n))
   
   return [mn, std]


In [18]:
# Promedio y medianas
#

import numpy as np
import clase.homework as hw

n = 51
# Normal distribution, mean=0, std=1
C = np.random.normal(0,1,51)

med = median(C)
[mean,std] = mn_std(C)

print("Número de puntos ", n)
print("Prom y std       %6.3f %6.3f %6.3f %6.3f" % (mean, std, np.mean(C), np.std(C)))
print("Mediana          %6.3f %6.3f" % (med, np.median(C)))
print('Arreglo organizado')
print(hw.quicksort(C))

print('')
n = 50
# Normal distribution, mean=0, std=1
D = np.random.normal(0,1,50)

med = median(D)
[mean,std] = mn_std(D)

print("Número de puntos ", n)
print("Prom y std       %6.3f %6.3f %6.3f %6.3f" % (mean, std, np.mean(D), np.std(D)))
print("Mediana          %6.3f %6.3f" % (med, np.median(D)))
print('Arreglo organizado')
print(hw.quicksort(D))


Número de puntos  51
Prom y std        0.116  0.927  0.116  0.927
Mediana          -0.030 -0.030
Arreglo organizado
[-2.14888109 -1.44221987 -1.1926355  -1.07060461 -1.05766476 -0.94523639
 -0.73565537 -0.72944442 -0.55571319 -0.5472187  -0.48093242 -0.4754207
 -0.46253161 -0.43454486 -0.41408303 -0.32812203 -0.31894129 -0.2755099
 -0.25159563 -0.24953061 -0.24757213 -0.23224472 -0.18446116 -0.14838506
 -0.11173593 -0.03020449 -0.01213908 -0.01024701  0.02258293  0.03578596
  0.13520559  0.1431334   0.19104834  0.22476866  0.24045204  0.29912448
  0.38293581  0.80946831  0.89101119  0.9239839   0.97409419  1.1857998
  1.24878137  1.32028227  1.32226069  1.42656585  1.43709968  1.60633461
  1.648577    2.12551921  2.41499161]

Número de puntos  50
Prom y std       -0.070  1.013 -0.070  1.013
Mediana          -0.018 -0.018
Arreglo organizado
[-2.61433441 -2.10376796 -1.98542228 -1.68932289 -1.60934959 -1.3903373
 -1.03554521 -0.93813447 -0.922675   -0.83294597 -0.77711132 -0.70853409
 -0

### Ejercicio 3

En Geología estructural, tectónica o sismología muchas veces se estudia los esfuerzos y se describen con el tensor de esfuerzos. Suponga que tenemos un tensor de esfuerzos horizontales (solo 2 dimensiones)
$$
\tau = 
\begin{bmatrix}
\tau_{xx} & \tau_{xy}\\
\tau_{yx} & \tau_{yy}\\
\end{bmatrix}
$$

Para un tensor de esfuerzos, siempre es posible encontrar una dirección de tal forma que no haya esfuerzos de cizalla ($\tau_{xy}=\tau_{yx}=0$). Cuando esto se obtiene, se dice que se encontró los ejes principales de esfuerzo. 
$$
\tau^R = 
\begin{bmatrix}
\tau_{1} & 0\\
0 & \tau_{2}\\
\end{bmatrix}
$$

Por convención, los ejes principales están organizados de tal forma que $|\tau_1|>|\tau_2|$.

Escriba un programa que determine que ángulo debe rotar la matriz $\mathbf{\tau}$ 
$$
\tau = \begin{bmatrix}
-27.0 & -7.1\\
-7.1 & -13.0\\
\end{bmatrix} = 
\begin{bmatrix}
\tau_{xx} & \tau_{xy}\\
\tau_{yx} & \tau_{yy}\\
\end{bmatrix}
$$

para obtener (lo más cercano posible) un tensor de esfuerzos con sus ejes principales. Para rotar el tensor un ángulo $\alpha$ debe realizar la operación matricial:
$$
\tau^R = R\tau R^T
$$
donde 
$$
R = 
\begin{bmatrix}
\cos(\alpha) & -\sin(\alpha)\\
\sin(\alpha) & \cos(\alpha)\\
\end{bmatrix}
$$

**Ayuda** Recuerde que debe cambiar el ángulo a radianes para calcular el coseno. Permita que el programa haga la búsqueda del ángulo por Ud., por ejemplo con un `for` loop.

*Nota**: El mismo (y mejor) resultado se puede obtener utilizando algoritmos de algebra lineal, por ejemplo utilizando los *eigenvalues* y *eigenvectors* de la matriz. Pero esto es para más adelante. 


In [108]:
def rot_mat(Cmat,deg):
    """
    Función para rotar un vector o matriz
    en dos dimensiones en espacio Euclidiano.
    Matriz o vector debe tener shape(2,X), donde
    x puede ser tan grande como quiera
    Entradas: 
      Cmat - matriz o vector a rotar
      deg  - ángulo de rotación, en grados
    Salidas:
      C    - matriz o vector rotado.
    """

    import numpy as np
    
    # convert angle to rad
    alpha = deg/180.0*np.pi
    
    # create rotation matrix
    R = np.zeros((2,2))
    R[0,0] = np.cos(alpha)
    R[0,1] = -np.sin(alpha)
    R[1,0] = np.sin(alpha)
    R[1,1] = np.cos(alpha)
    
    Rt = np.transpose(R)

    C1 = np.matmul(R,Cmat)
    C  = np.matmul(C1,Rt)
    
    return C,R

In [109]:
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

tau = np.array([[-27.0, -7.1],[-7.1, -13.0]],dtype=float)

print('Tensor de Esfuerzos')
print(tau)

ang = np.arange(-90,90,0.1)

for alpha in ang :
    C2,R = rot_mat(tau,alpha)
    if (abs(C2[0,0])<abs(C2[1,1])):
        continue
    if (abs(C2[1,0])<0.01):
        print('Ángulo rotación %4.1f' %(alpha))
        print('Tensor de Esfuerzos Principales')
        print(C2)
        print('Matriz de rotación')
        print(R)
        print('')

Tensor de Esfuerzos
[[-27.000 -7.100]
 [-7.100 -13.000]]
Ángulo rotación -22.7
Tensor de Esfuerzos Principales
[[-29.970 -0.001]
 [-0.001 -10.030]]
Matriz de rotación
[[ 0.923  0.386]
 [-0.386  0.923]]

