In [24]:
# mult_table
# Genere una tabla de multiplicar para los números del 1 al 9

import numpy as np

i = np.arange(9)+1
j = np.arange(10)+1

#np.set_printoptions(precision=3)
for val1 in i:
    val2 = val1*j
    print ("Table of ", val1)
    print(val2)
   

Table of  1
[ 1  2  3  4  5  6  7  8  9 10]
Table of  2
[ 2  4  6  8 10 12 14 16 18 20]
Table of  3
[ 3  6  9 12 15 18 21 24 27 30]
Table of  4
[ 4  8 12 16 20 24 28 32 36 40]
Table of  5
[ 5 10 15 20 25 30 35 40 45 50]
Table of  6
[ 6 12 18 24 30 36 42 48 54 60]
Table of  7
[ 7 14 21 28 35 42 49 56 63 70]
Table of  8
[ 8 16 24 32 40 48 56 64 72 80]
Table of  9
[ 9 18 27 36 45 54 63 72 81 90]
